import { useState } from 'react'
import { BadgePlus, CheckCircle2, ExternalLink, Printer, Search, ShieldAlert, Ticket, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { SectionHead } from '../components/Layout'
import { QrCode } from '../components/QrCode'
import { EmblemPlaceholder } from '../components/EmblemPlaceholder'
import { accessTokenRepository, agentRepository, emblemRepository, enrollmentRepository, sessionRepository } from '../repositories'
import { centralRegistry } from '../services/centralRegistry'
import { cacheRegistrationPrintBatch, readRegistrationPrintTokens, storeRegistrationPrintTokens } from '../services/registrationPrintCache'
import { buildAccessUrl, isLocalOnlyOrigin } from '../utils/accessUrl'
import { assetUrl } from '../utils/basePath'
import { useAsyncResource } from '../hooks/useAsyncResource'
import { useFieldAgentSearch } from '../hooks/useFieldAgentSearch'
import { useWorkingSession } from '../auth/WorkingSessionContext'
import { useStaffAuth } from '../auth/StaffAuthContext'
import { RegistrationControl } from '../components/RegistrationControl'
import { AgentDetail } from '../components/AgentDetail'

export function Admin({ view = 'overview' }) {
  const { profile } = useStaffAuth()
  const { sessions, currentSession: current, refresh: refreshSessions } = useWorkingSession()
  const [revision, setRevision] = useState(0)
  const summary = useAsyncResource(async () => { const [agents, roster, tokens] = await Promise.all([agentRepository.getAll(), enrollmentRepository.getBySession(current.id), accessTokenRepository.getMetadataBySession(current.id)]); return { agents: agents.length, roster: roster.length, tokens } }, [current.id, revision])
  const [query, setQuery] = useState(''); const search = useFieldAgentSearch(query, current.id); const [selectedId, setSelectedId] = useState(''); const selected = search.results.find((agent) => agent.id === selectedId)
  const [message, setMessage] = useState(''); const [ceremony, setCeremony] = useState(null); const [tokenCount, setTokenCount] = useState(1); const [selectedTokenIds, setSelectedTokenIds] = useState([]); const [lastCreatedIds, setLastCreatedIds] = useState([]); const [registrationTokens, setRegistrationTokens] = useState(() => readRegistrationPrintTokens()); const [creatingTokens, setCreatingTokens] = useState(false)
  const [sessionForm, setSessionForm] = useState({ id: '', name: '', startDate: '', endDate: '', status: 'PREPARING' })
  const localOnlyOrigin = isLocalOnlyOrigin(); const isOwner = profile.role === 'OWNER'

  const refreshOperationalData = () => setRevision((value) => value + 1)
  const addReturning = async (agent) => { try { const result = await centralRegistry.registerReturning(agent.id, current.id); setCeremony({ ...result, agent: { ...result.agent, emblem: agent.emblem }, session: current }); refreshOperationalData(); setMessage('') } catch (error) { setMessage(error.message) } }
  const createTokens = async () => { if (localOnlyOrigin || creatingTokens) return; setCreatingTokens(true); setMessage(''); try { const created = await accessTokenRepository.createUniversalBatch(tokenCount); const stored = storeRegistrationPrintTokens(created.map((token) => ({ ...token, accessUrl: buildAccessUrl(token.rawToken) }))); const ids = created.map((item) => item.id); setRegistrationTokens(stored); setLastCreatedIds(ids); setSelectedTokenIds(ids); setMessage(`已產生 ${created.length} 張 Universal Registration Credentials；尚未分配 Session。`); refreshOperationalData() } catch (error) { setMessage(error.message) } finally { setCreatingTokens(false) } }
  const toggleToken = (id) => setSelectedTokenIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id])
  const printLayoutUrl = (ids) => { const batch = cacheRegistrationPrintBatch(registrationTokens.filter((item) => ids.includes(item.id))); return `/admin/qr-print?batch=${encodeURIComponent(batch)}` }
  const saveSession = async (event) => { event.preventDefault(); try { await sessionRepository.manage(sessionForm); await refreshSessions(); setSessionForm({ id: '', name: '', startDate: '', endDate: '', status: 'PREPARING' }); setMessage('Session 已儲存並寫入 audit log。') } catch (error) { setMessage(error.message) } }
  const deleteAgent = async () => { if (!selected || !isOwner) return; if (!window.confirm(`永久刪除 ${selected.id} / ${selected.codename}？此操作無法復原。`)) return; if (!window.confirm(`第二次確認：將刪除 ${selected.missions.length} 筆 Enrollment、撤銷相關憑證並移除徽章。確定繼續？`)) return; try { const result = await agentRepository.deletePermanently(selected.id); const prefixes = [result.emblemPath, `agents/${result.agentUuid}`, ...(result.tokenHashes || []).map((hash) => `temporary/${hash}`)]; await emblemRepository.removeByPrefixes(prefixes); setSelectedId(''); setQuery(''); refreshOperationalData(); setMessage(`${result.permanentAgentId} 已永久刪除；序號未自動補洞。`) } catch (error) { setMessage(`刪除未完整完成：${error.message}`) } }
  const resequence = async () => { if (!isOwner) return; if (!window.confirm(`將依首次登錄時間重新編排目前 ${summary.data?.agents ?? 0} 位探員的所有 AGENT-xxxxxx。確定繼續？`)) return; if (!window.confirm('第二次確認：這會改變對外永久探員序號，但 UUID 與所有關聯不變。')) return; try { const result = await agentRepository.resequencePermanentIds(); setSelectedId(''); setQuery(''); refreshOperationalData(); setMessage(`已重新整理 ${result.affectedCount} 位探員；下一號為 AGENT-${String(result.nextNumber).padStart(6, '0')}。`) } catch (error) { setMessage(error.message) } }

  if (ceremony) return <section className="success-panel returning-success"><img className="registration-official-emblem" src={assetUrl('assets/time-emblem.png')} alt="T.I.M.E. 正式局徽" /><div className="success-mark"><CheckCircle2 /></div><span className="eyebrow">IDENTITY MATCH CONFIRMED</span><h1>RETURNING AGENT VERIFIED</h1><h2>回歸探員身分確認</h2><p className="success-welcome">WELCOME BACK, AGENT {ceremony.agent.codename}.</p>{ceremony.agent.emblem && <img className="success-emblem" src={ceremony.agent.emblem} alt="探員徽章" />}<div className="receipt"><span>AGENT NUMBER<strong>{ceremony.enrollment.displayAgentNumber}</strong></span><span>CODENAME<strong>{ceremony.agent.codename}</strong></span><span>CLASS<strong>RETURNING AGENT</strong></span></div><button className="button" onClick={() => setCeremony(null)}>返回管理終端</button></section>
  const showOverview = view === 'overview'
  const showOperations = view === 'operations'
  const showAgents = view === 'agents' || view === 'returning'
  const showMissions = view === 'missions'
  return <><SectionHead eyebrow="BUREAU ADMINISTRATION // AUTHORIZED" title={view === 'agents' ? '探員搜尋' : view === 'returning' ? '探員回歸' : view === 'missions' ? '任務管理' : view === 'operations' ? '現場控制中心' : 'Bureau Console 控制中心'}>目前作業梯次：{current.name}。所有正式資料均以 Supabase 為準。</SectionHead>
    <div className="admin-stats"><span>ALL AGENTS<strong>{summary.data?.agents ?? '—'}</strong></span><span>SESSIONS<strong>{sessions.length}</strong></span><span>CURRENT ENROLLMENTS<strong>{summary.data?.roster ?? '—'}</strong></span></div>
    {showOverview && <div className="admin-quick-links"><Link className="button button--ghost" to="/admin/staff"><Users size={16} />工作人員管理</Link><Link className="button button--ghost" target="_blank" to={`/wall?session=${encodeURIComponent(current.id)}`}><ExternalLink size={16} />開啟此梯投影牆</Link></div>}
    {message && <p className="admin-message">{message}</p>}
    {showMissions && <section className="token-console" id="credentials"><header><div><span>UNIVERSAL REGISTRATION CREDENTIALS</span><h2>通用首次入局憑證</h2><p>建立時不屬於任何 Session；掃描進入 Waiting Pool，Staff 授權時才正式綁定。</p></div><Ticket /></header>{localOnlyOrigin && <div className="qr-origin-warning"><strong>目前使用本機網址開啟管理端。</strong><span>請改用區域網路 IP 開啟後再產生供手機使用的 QR。</span></div>}<div className="token-actions"><div className="token-presets">{[1,5,10].map((count) => <button className={Number(tokenCount) === count ? 'is-active' : ''} type="button" key={count} onClick={() => setTokenCount(count)}>{count} 張</button>)}<label>自訂<input type="number" min="1" max="500" value={tokenCount} onChange={(event) => setTokenCount(event.target.value)} /></label></div><button className="button" disabled={localOnlyOrigin || creatingTokens} onClick={createTokens}>{creatingTokens ? '正在產生……' : '產生通用憑證'}</button></div>
      {!!registrationTokens.length && <div className="token-selection-bar" id="qr-print"><span>工作階段內共 {registrationTokens.length} 張／已選 {selectedTokenIds.length} 張</span><button type="button" onClick={() => setSelectedTokenIds(registrationTokens.map((item) => item.id))}>全選</button><button type="button" onClick={() => setSelectedTokenIds([])}>取消全選</button>{selectedTokenIds.length ? <Link className="button button--ghost" to={printLayoutUrl(selectedTokenIds)}><Printer size={16} />列印已選 QR</Link> : null}{lastCreatedIds.length ? <Link className="button" to={printLayoutUrl(lastCreatedIds)}><Printer size={16} />列印剛產生的 {lastCreatedIds.length} 張</Link> : null}</div>}
      <div className="token-grid">{registrationTokens.map((access) => { const checked = selectedTokenIds.includes(access.id); return <article className={`token-card ${checked ? 'is-selected' : ''}`} key={access.id}><label className="token-check"><input type="checkbox" checked={checked} onChange={() => toggleToken(access.id)} /><span>{access.shortCode}</span></label><div className="token-paper-head"><img src={assetUrl('assets/time-emblem.png')} alt="T.I.M.E. 局徽" /><div><span>{access.shortCode}</span><strong>UNASSIGNED</strong></div><b>UNIVERSAL</b></div><QrCode value={access.accessUrl} label={access.shortCode} downloadable /></article> })}</div>
      <div id="token-metadata"><h3>REGISTRATION TOKEN METADATA</h3><div className="token-metadata">{(summary.data?.tokens || []).map((token) => <div key={token.id}><strong>{token.shortCode}</strong><span>{token.status}</span><span>{new Date(token.createdAt).toLocaleString('zh-TW')}</span><span>{token.codename || '尚未綁定 Agent'}</span><small>{registrationTokens.some((cached) => cached.id === token.id) ? '原始 QR 位於目前工作階段' : '原始 QR 已不在目前工作階段'}</small></div>)}</div></div>
    </section>}
    {showOperations && <div id="waiting-pool"><span id="authorization" /><RegistrationControl /></div>}

    {showAgents && <><div className="search-box"><Search /><input value={query} onChange={(event) => setQuery(event.target.value.toUpperCase())} placeholder="搜尋 Codename、T-xxx、Permanent Agent ID 或 REG-xxxx" /><kbd>ADMIN</kbd></div>{search.error && <p className="admin-message">{search.error}</p>}
    <div className="admin-layout"><section className="admin-results"><h2>AGENT DIRECTORY // {search.loading ? 'READING' : search.results.length}</h2>{search.results.map((agent) => <article className={`admin-agent ${selectedId === agent.id ? 'is-selected' : ''}`} key={agent.id} onClick={() => setSelectedId(agent.id)}>{agent.emblem ? <img src={agent.emblem} alt="" /> : <EmblemPlaceholder />}<div><span>{agent.id}</span><strong>{agent.codename}</strong><small>{agent.currentEnrollment ? `${agent.currentEnrollment.displayAgentNumber} // ${agent.currentEnrollment.completionStatus}` : '尚未加入目前梯次'} // {agent.missions.length} 次任務</small></div><button className="button button--ghost" disabled={Boolean(agent.currentEnrollment)} onClick={(event) => { event.stopPropagation(); void addReturning(agent) }}><BadgePlus size={15} />{agent.currentEnrollment ? '已在本梯次' : '加入目前梯次'}</button></article>)}</section>
      <aside className="admin-detail"><AgentDetail agent={selected} isOwner={isOwner} onDelete={deleteAgent} /></aside></div></>}

    {showMissions && <section className="session-overview" id="sessions"><h2>SESSION MANAGEMENT</h2><form className="session-form" onSubmit={saveSession}><input required placeholder="2026-SUMMER-02" value={sessionForm.id} onChange={(event) => setSessionForm({ ...sessionForm, id: event.target.value.toUpperCase() })} /><input required placeholder="Session 名稱" value={sessionForm.name} onChange={(event) => setSessionForm({ ...sessionForm, name: event.target.value })} /><input type="date" value={sessionForm.startDate} onChange={(event) => setSessionForm({ ...sessionForm, startDate: event.target.value })} /><input type="date" value={sessionForm.endDate} onChange={(event) => setSessionForm({ ...sessionForm, endDate: event.target.value })} /><select value={sessionForm.status} onChange={(event) => setSessionForm({ ...sessionForm, status: event.target.value })}><option>PREPARING</option><option>ACTIVE</option><option>ARCHIVED</option></select><button className="button">建立／更新 Session</button></form>{sessions.map((session) => <div key={session.id}><strong>{session.name}</strong><span>{session.status === 'PLANNED' ? 'PREPARING' : session.status}</span><small>{session.id}</small></div>)}</section>}
    {showAgents && isOwner && <section className="owner-danger-zone"><ShieldAlert /><div><span>OWNER ONLY // IRREVERSIBLE ADMINISTRATION</span><h2>永久探員序號管理</h2><p>只改變公開的 AGENT-xxxxxx；UUID、Enrollment、Token 與 Storage 關聯均保持不變。</p></div><strong>{summary.data?.agents ?? 0} AGENTS</strong><button className="button button--danger" onClick={resequence}>重新整理永久探員序號</button></section>}
  </>
}
