import { useCallback, useMemo, useState } from 'react'
import { BadgePlus, CheckCircle2, Printer, Search, Save, Ticket } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmblemCapture } from '../components/EmblemCapture'
import { SectionHead } from '../components/Layout'
import { agentStore } from '../data/agentStore'
import { enrollmentStore } from '../data/enrollmentStore'
import { sessionStore } from '../data/sessionStore'
import { useRegistryData } from '../hooks/useAgents'
import { agentRegistry } from '../services/agentRegistry'
import { QrCode } from '../components/QrCode'
import { buildAccessUrl, isLocalOnlyOrigin } from '../utils/accessUrl'
import { accessTokenRepository } from '../repositories'
import { cacheRegistrationPrintBatch } from '../services/registrationPrintCache'
import { assetUrl } from '../utils/basePath'

export function Admin() {
  const data = useRegistryData(); const current = sessionStore.getCurrent(); const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState(''); const [message, setMessage] = useState(''); const [ceremony, setCeremony] = useState(null); const [emblem, setEmblem] = useState({ source: '', cropped: '' }); const [tokenCount, setTokenCount] = useState(1); const [selectedTokenIds, setSelectedTokenIds] = useState([]); const [lastCreatedIds, setLastCreatedIds] = useState([]); const [registrationTokens, setRegistrationTokens] = useState([]); const [creatingTokens, setCreatingTokens] = useState(false); const updateEmblem = useCallback(setEmblem, [])
  const localOnlyOrigin = isLocalOnlyOrigin()
  const results = useMemo(() => agentStore.search(query), [data.agents, query]); const selected = data.agents.find((a) => a.id === selectedId); const history = selected ? enrollmentStore.getByAgent(selected.id) : []
  const addReturning = (agent) => { try { const result = agentRegistry.registerReturning(agent.id); if (result.alreadyEnrolled) setMessage('此探員已加入目前梯次，未建立重複紀錄。'); else { setCeremony(result); setMessage('') } } catch (error) { setMessage(error.message) } }
  const saveEmblem = () => { if (selected && emblem.cropped) { agentStore.setEmblem(selected.id, emblem.cropped); setMessage('永久識別徽章已更新。'); setEmblem({ source: '', cropped: '' }) } }
  const createTokens = async () => { if (localOnlyOrigin || creatingTokens) return; setCreatingTokens(true); setMessage(''); try { const created = await accessTokenRepository.createBatch(tokenCount, current.id); const ids = created.map((item) => item.id); setRegistrationTokens((tokens) => [...created, ...tokens]); setLastCreatedIds(ids); setSelectedTokenIds(ids); const inspections = await Promise.all(created.map((item) => accessTokenRepository.inspect(item.rawToken))); const verified = inspections.every((inspection, index) => inspection.state === 'UNUSED' && inspection.shortCode === created[index].shortCode && inspection.session?.id === created[index].sessionId); if (!verified) throw new Error('憑證已建立，但中央驗證結果不一致。請勿列印這批 QR，並洽系統管理者。'); setMessage(`已產生 ${created.length} 張 ${current.name} 首次入局憑證；Supabase 驗證全部為 UNUSED，並已自動選取。`) } catch (error) { setMessage(error.message) } finally { setCreatingTokens(false) } }
  const toggleToken = (id) => setSelectedTokenIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id])
  const printLayoutUrl = (ids) => { const batch = cacheRegistrationPrintBatch(registrationTokens.filter((item) => ids.includes(item.id))); return `/admin/qr-print?batch=${encodeURIComponent(batch)}` }
  if (ceremony) return <section className="success-panel returning-success"><img className="registration-official-emblem" src={assetUrl('assets/time-emblem.png')} alt="T.I.M.E. 正式局徽" /><div className="success-mark"><CheckCircle2 /></div><span className="eyebrow">IDENTITY MATCH CONFIRMED</span><h1>RETURNING AGENT VERIFIED</h1><h2>回歸探員身分確認</h2><p className="success-welcome">WELCOME BACK, AGENT {ceremony.agent.codename}.</p><img className="success-emblem" src={ceremony.agent.emblem} alt="探員徽章" /><div className="receipt"><span>AGENT NUMBER<strong>{ceremony.enrollment.displayAgentNumber}</strong></span><span>CODENAME<strong>{ceremony.agent.codename}</strong></span><span>CLASS<strong>RETURNING AGENT</strong></span></div><p>{ceremony.session.name} // 首次登錄 {new Date(ceremony.agent.firstRegisteredAt).getFullYear()}</p><button className="button" onClick={() => setCeremony(null)}>返回管理終端</button></section>
  return <><SectionHead eyebrow="BUREAU ADMINISTRATION // AUTHORIZED" title="任務與探員管理終端">目前任務梯次：{current.name}。此區僅供 OWNER 與 ADMIN 使用。</SectionHead>
    <div className="admin-stats"><span>ALL AGENTS<strong>{data.agents.length}</strong></span><span>SESSIONS<strong>{data.sessions.length}</strong></span><span>CURRENT ENROLLMENTS<strong>{data.roster.length}</strong></span></div>
    <section className="token-console"><header><div><span>REGISTRATION CREDENTIALS</span><h2>產生首次入局憑證</h2><p>每張 QR 僅能建立一次永久探員身分，並綁定目前梯次：{current.name}</p></div><Ticket /></header>{localOnlyOrigin && <div className="qr-origin-warning" role="alert"><strong>目前使用本機網址開啟管理端。</strong><span>由此產生的 QR Code 無法供其他裝置使用。請改用區域網路 IP 開啟管理端後再產生憑證。</span></div>}<div className="token-actions"><div className="token-presets">{[1, 5, 10].map((count) => <button className={Number(tokenCount) === count ? 'is-active' : ''} type="button" key={count} onClick={() => setTokenCount(count)}>{count} 張</button>)}<label>自訂<input type="number" min="1" max="100" value={tokenCount} onChange={(e) => setTokenCount(e.target.value)} /></label></div><button className="button" disabled={localOnlyOrigin || creatingTokens} onClick={createTokens}>{creatingTokens ? '正在產生……' : '產生憑證'}</button></div>
      {!!registrationTokens.length && <div className="token-selection-bar"><span>已選取 {selectedTokenIds.length} 張</span><button type="button" onClick={() => setSelectedTokenIds(registrationTokens.map((item) => item.id))}>全選</button><button type="button" onClick={() => setSelectedTokenIds([])}>取消全選</button>{selectedTokenIds.length && !localOnlyOrigin ? <Link className="button button--ghost" target="_blank" rel="noopener noreferrer" to={printLayoutUrl(selectedTokenIds)}><Printer size={16} />列印已選 QR</Link> : <button className="button button--ghost" disabled><Printer size={16} />列印已選 QR</button>}{lastCreatedIds.length && !localOnlyOrigin ? <Link className="button" target="_blank" rel="noopener noreferrer" to={printLayoutUrl(lastCreatedIds)}><Printer size={16} />列印剛產生的 {lastCreatedIds.length} 張</Link> : <button className="button" disabled><Printer size={16} />列印剛產生的 {lastCreatedIds.length} 張</button>}</div>}
      <div className="token-grid">{registrationTokens.map((access) => { const url = buildAccessUrl(access.rawToken); const checked = selectedTokenIds.includes(access.id); return <article className={`token-card ${checked ? 'is-selected' : ''}`} key={access.id}><label className="token-check"><input type="checkbox" checked={checked} onChange={() => toggleToken(access.id)} /><span>選取 {access.shortCode}</span></label><div className="token-paper-head"><img src={assetUrl('assets/time-emblem.png')} alt="T.I.M.E. 局徽" /><div><span>{access.shortCode}</span><strong>{current.id === access.sessionId ? current.name : sessionStore.getById(access.sessionId)?.name}</strong></div><b className={access.status.toLowerCase()}>{access.status}</b></div>{localOnlyOrigin ? <div className="qr-host-blocked">請使用區域網路 IP 開啟管理端以顯示 QR</div> : <><QrCode value={url} label={access.shortCode} downloadable /><code>{url}</code></>}<dl><div><dt>CREATED</dt><dd>{new Date(access.createdAt).toLocaleString('zh-TW')}</dd></div><div><dt>AGENT</dt><dd>尚未使用</dd></div></dl></article> })}</div>
    </section>
    <div className="search-box"><Search /><input value={query} onChange={(e) => setQuery(e.target.value.toUpperCase())} placeholder="搜尋 Codename、Agent ID 或 access token" /><kbd>ADMIN</kbd></div>{message && <p className="admin-message">{message}</p>}
    <div className="admin-layout"><section className="admin-results"><h2>AGENT DIRECTORY</h2>{results.map((agent) => { const missions = enrollmentStore.getByAgent(agent.id); const joined = enrollmentStore.exists(agent.id, current.id); return <article className={`admin-agent ${selectedId === agent.id ? 'is-selected' : ''}`} key={agent.id} onClick={() => setSelectedId(agent.id)}><img src={agent.emblem} alt="" /><div><span>{agent.id}</span><strong>{agent.codename}</strong><small>首次登錄 {new Date(agent.firstRegisteredAt).getFullYear()} // {missions.length} 次任務</small></div><button className="button button--ghost" disabled={joined} onClick={(e) => { e.stopPropagation(); addReturning(agent) }}><BadgePlus size={15} />{joined ? '已在本梯次' : '加入目前梯次'}</button></article> })}</section>
      <aside className="admin-detail">{selected ? <><h2>{selected.codename}</h2><p>{selected.id}</p><label>CODENAME<input value={selected.codename} onChange={(e) => agentStore.update(selected.id, { codename: e.target.value.toUpperCase().replace(/[^A-Z]/g, '') })} /></label><label>STATUS<select value={selected.status} onChange={(e) => agentStore.update(selected.id, { status: e.target.value })}><option>ACTIVE</option><option>INACTIVE</option></select></label><h3>MISSION HISTORY</h3>{history.map((item) => <div className="admin-mission" key={item.id}><span>{sessionStore.getById(item.sessionId)?.name}</span><strong>{item.displayAgentNumber}</strong></div>)}<h3>REPLACE EMBLEM</h3><EmblemCapture value={emblem} onChange={updateEmblem} /><button className="button" disabled={!emblem.cropped} onClick={saveEmblem}><Save size={15} />儲存徽章</button><Link className="text-link" to={`/agent/${selected.id}`}>開啟永久探員檔案</Link></> : <p>選擇一位探員以檢視與編輯資料。</p>}</aside></div>
    <section className="session-overview"><h2>SESSION OVERVIEW</h2>{data.sessions.map((session) => <div key={session.id}><strong>{session.name}</strong><span>{enrollmentStore.getBySession(session.id).length} 位探員</span><small>{session.id} // {session.status}</small></div>)}</section>
  </>
}
