import { useState } from 'react'
import { BadgePlus, CheckCircle2, Printer, Search, Ticket } from 'lucide-react'
import { Link } from 'react-router-dom'
import { SectionHead } from '../components/Layout'
import { QrCode } from '../components/QrCode'
import { EmblemPlaceholder } from '../components/EmblemPlaceholder'
import { accessTokenRepository, agentRepository, enrollmentRepository, sessionRepository } from '../repositories'
import { centralRegistry } from '../services/centralRegistry'
import { cacheRegistrationPrintBatch } from '../services/registrationPrintCache'
import { buildAccessUrl, isLocalOnlyOrigin } from '../utils/accessUrl'
import { assetUrl } from '../utils/basePath'
import { campConfig } from '../config/campConfig'
import { useAsyncResource } from '../hooks/useAsyncResource'
import { useFieldAgentSearch } from '../hooks/useFieldAgentSearch'

export function Admin() {
  const currentResource = useAsyncResource(() => sessionRepository.getCurrent(), [])
  const summary = useAsyncResource(async () => { const [agents, sessions, roster] = await Promise.all([agentRepository.getAll(), sessionRepository.getAll(), enrollmentRepository.getBySession(campConfig.currentSessionId)]); return { agents: agents.length, sessions: sessions.length, roster: roster.length } }, [])
  const current = currentResource.data || { id: campConfig.currentSessionId, name: campConfig.currentSessionId }
  const [query, setQuery] = useState(''); const search = useFieldAgentSearch(query, current.id); const [selectedId, setSelectedId] = useState(''); const selected = search.results.find((agent) => agent.id === selectedId)
  const [message, setMessage] = useState(''); const [ceremony, setCeremony] = useState(null); const [tokenCount, setTokenCount] = useState(1); const [selectedTokenIds, setSelectedTokenIds] = useState([]); const [lastCreatedIds, setLastCreatedIds] = useState([]); const [registrationTokens, setRegistrationTokens] = useState([]); const [creatingTokens, setCreatingTokens] = useState(false)
  const localOnlyOrigin = isLocalOnlyOrigin()
  const addReturning = async (agent) => { try { const result = await centralRegistry.registerReturning(agent.id, current.id); setCeremony({ ...result, agent: { ...result.agent, emblem: agent.emblem, firstRegisteredAt: agent.firstRegisteredAt }, session: current }); setMessage('') } catch (error) { setMessage(error.message) } }
  const createTokens = async () => { if (localOnlyOrigin || creatingTokens) return; setCreatingTokens(true); setMessage(''); try { const created = await accessTokenRepository.createBatch(tokenCount, current.id); const ids = created.map((item) => item.id); setRegistrationTokens((tokens) => [...created, ...tokens]); setLastCreatedIds(ids); setSelectedTokenIds(ids); const inspections = await Promise.all(created.map((item) => accessTokenRepository.inspect(item.rawToken))); const verified = inspections.every((inspection, index) => inspection.state === 'UNUSED' && inspection.shortCode === created[index].shortCode && inspection.session?.id === created[index].sessionId); if (!verified) throw new Error('憑證已建立，但中央驗證結果不一致。請勿列印這批 QR。'); setMessage(`已產生 ${created.length} 張憑證；Supabase 驗證全部為 UNUSED。`) } catch (error) { setMessage(error.message) } finally { setCreatingTokens(false) } }
  const toggleToken = (id) => setSelectedTokenIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id])
  const printLayoutUrl = (ids) => { const batch = cacheRegistrationPrintBatch(registrationTokens.filter((item) => ids.includes(item.id))); return `/admin/qr-print?batch=${encodeURIComponent(batch)}` }
  if (ceremony) return <section className="success-panel returning-success"><img className="registration-official-emblem" src={assetUrl('assets/time-emblem.png')} alt="T.I.M.E. 正式局徽" /><div className="success-mark"><CheckCircle2 /></div><span className="eyebrow">IDENTITY MATCH CONFIRMED</span><h1>RETURNING AGENT VERIFIED</h1><h2>回歸探員身分確認</h2><p className="success-welcome">WELCOME BACK, AGENT {ceremony.agent.codename}.</p>{ceremony.agent.emblem && <img className="success-emblem" src={ceremony.agent.emblem} alt="探員徽章" />}<div className="receipt"><span>AGENT NUMBER<strong>{ceremony.enrollment.displayAgentNumber}</strong></span><span>CODENAME<strong>{ceremony.agent.codename}</strong></span><span>CLASS<strong>RETURNING AGENT</strong></span></div><button className="button" onClick={() => setCeremony(null)}>返回管理終端</button></section>
  return <><SectionHead eyebrow="BUREAU ADMINISTRATION // AUTHORIZED" title="任務與探員管理終端">目前任務梯次：{current.name}。正式資料由 Supabase 中央檔案提供。</SectionHead>
    <div className="admin-stats"><span>ALL AGENTS<strong>{summary.data?.agents ?? '—'}</strong></span><span>SESSIONS<strong>{summary.data?.sessions ?? '—'}</strong></span><span>CURRENT ENROLLMENTS<strong>{summary.data?.roster ?? '—'}</strong></span></div>
    <section className="token-console"><header><div><span>REGISTRATION CREDENTIALS</span><h2>產生首次入局憑證</h2><p>每張 QR 僅能建立一次永久探員身分，並綁定目前梯次：{current.name}</p></div><Ticket /></header>{localOnlyOrigin && <div className="qr-origin-warning"><strong>目前使用本機網址開啟管理端。</strong><span>請改用區域網路 IP 開啟管理端後再產生憑證。</span></div>}<div className="token-actions"><div className="token-presets">{[1,5,10].map((count) => <button className={Number(tokenCount) === count ? 'is-active' : ''} type="button" key={count} onClick={() => setTokenCount(count)}>{count} 張</button>)}<label>自訂<input type="number" min="1" max="100" value={tokenCount} onChange={(event) => setTokenCount(event.target.value)} /></label></div><button className="button" disabled={localOnlyOrigin || creatingTokens} onClick={createTokens}>{creatingTokens ? '正在產生……' : '產生憑證'}</button></div>
      {!!registrationTokens.length && <div className="token-selection-bar"><span>已選取 {selectedTokenIds.length} 張</span><button type="button" onClick={() => setSelectedTokenIds(registrationTokens.map((item) => item.id))}>全選</button><button type="button" onClick={() => setSelectedTokenIds([])}>取消全選</button>{selectedTokenIds.length ? <Link className="button button--ghost" target="_blank" to={printLayoutUrl(selectedTokenIds)}><Printer size={16} />列印已選 QR</Link> : null}{lastCreatedIds.length ? <Link className="button" target="_blank" to={printLayoutUrl(lastCreatedIds)}><Printer size={16} />列印剛產生的 {lastCreatedIds.length} 張</Link> : null}</div>}
      <div className="token-grid">{registrationTokens.map((access) => { const url = buildAccessUrl(access.rawToken); const checked = selectedTokenIds.includes(access.id); return <article className={`token-card ${checked ? 'is-selected' : ''}`} key={access.id}><label className="token-check"><input type="checkbox" checked={checked} onChange={() => toggleToken(access.id)} /><span>選取 {access.shortCode}</span></label><div className="token-paper-head"><img src={assetUrl('assets/time-emblem.png')} alt="T.I.M.E. 局徽" /><div><span>{access.shortCode}</span><strong>{current.name}</strong></div><b className="unused">UNUSED</b></div><QrCode value={url} label={access.shortCode} downloadable /><code>{url}</code></article> })}</div>
    </section>
    <div className="search-box"><Search /><input value={query} onChange={(event) => setQuery(event.target.value.toUpperCase())} placeholder="搜尋 Codename、T-xxx、Permanent Agent ID 或 REG-xxxx" /><kbd>ADMIN</kbd></div>{message && <p className="admin-message">{message}</p>}{search.error && <p className="admin-message">{search.error}</p>}
    <div className="admin-layout"><section className="admin-results"><h2>AGENT DIRECTORY // {search.loading ? 'READING' : search.results.length}</h2>{search.results.map((agent) => <article className={`admin-agent ${selectedId === agent.id ? 'is-selected' : ''}`} key={agent.id} onClick={() => setSelectedId(agent.id)}>{agent.emblem ? <img src={agent.emblem} alt="" /> : <EmblemPlaceholder />}<div><span>{agent.id}</span><strong>{agent.codename}</strong><small>{agent.currentEnrollment ? `${agent.currentEnrollment.displayAgentNumber} // ${agent.currentEnrollment.completionStatus}` : '尚未加入目前梯次'} // {agent.missions.length} 次任務</small></div><button className="button button--ghost" disabled={Boolean(agent.currentEnrollment)} onClick={(event) => { event.stopPropagation(); void addReturning(agent) }}><BadgePlus size={15} />{agent.currentEnrollment ? '已在本梯次' : '加入目前梯次'}</button></article>)}</section>
      <aside className="admin-detail">{selected ? <><h2>{selected.codename}</h2><p>{selected.id}</p><div className="field-status"><span>首次登錄<strong>{new Date(selected.firstRegisteredAt).getFullYear()}</strong></span><span>徽章<strong>{selected.emblemPath ? '已完成' : '尚未完成'}</strong></span><span>本梯 Enrollment<strong>{selected.currentEnrollment?.completionStatus || '尚未加入'}</strong></span><span>身分類別<strong>{selected.currentEnrollment?.returningAgent ? 'RETURNING' : 'FIRST REGISTRATION'}</strong></span></div><h3>MISSION HISTORY</h3>{selected.missions.map((mission) => <div className="admin-mission" key={mission.enrollmentId}><span>{mission.sessionName}</span><strong>{mission.displayAgentNumber} // {mission.completionStatus}</strong></div>)}</> : <p>搜尋並選擇一位探員，即可判斷登錄、徽章與本梯任務狀態。</p>}</aside></div>
  </>
}
